name: ci-ginkgo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Declare default permissions as read only.
permissions: read-all

jobs:
  ginkgo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Test connectivity
        run: kubectl get no
      - name: Deploy wordpress application
        run: kubectl apply -f ./tests/recommend/res/wordpress-mysql-deployment.yaml
      - name: Wait for pods
        run: kubectl -n wordpress-mysql wait --for=condition=ready pod --all --timeout=5m
      - name: Test kArmor recommend using Ginkgo
        run: |
          make install
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          make recommend -C tests/
        timeout-minutes: 30
        
